apiVersion: v2
name: walnut
description: OpenAI-compatible inference server for walnut.
type: application
version: 0.2.1
appVersion: 0.1.0
home: https://github.com/thomasbarrett/walnut
sources:
  - https://github.com/thomasbarrett/walnut
